README.md, api/testrun.go, cmd/calllog.go, cmd/root.go, cmd/test_run_logs.go, cmd/testrun.go
This PR adds the `test-run` command and it's (currently) only sub-command `logs`. It will fetch the request log up to the first 10k items. The log contains of:
* time (epoch in seconds)
* HTTP verb
* HTTP host
* request path
* HTTP Status Code
* response size (in Bytes)
* duration (in ms)
* request tag
separated by `;`.
```
forge test-run logs <test-run-ref>
```
`<test-run-ref>` is in the form of:
* `$organisation/$test-case/$test-run-id` like `stormforger/demo/42`, or
* `$organisation/$test-case/test_runs/$test-run-id` like `stormforger/demo/test_runs/42`
`<test-run-ref>` can also be the test run uid (not supported by the API yet).
Using `--full` you will get the entire request/call log.
Using `--output=requests.log` you can save the output directly to file, instead of printing it to …
=> Test Run Call Logs

.travis.yml, Makefile, api/client.go, api/file_fixture.go, api/har.go, api/testcase.go, api/testcase/main.go, cmd/datasource.go, cmd/organisation.go, cmd/testcase.go, cmd/testcase_create.go, cmd/testcase_list.go, cmd/testcase_update.go, cmd/testcase_validate.go, cmd/utils.go, testdata/cases/invalid.js, testdata/cases/invalid_syntax.js, testdata/cases/valid.js, testdata/cases/valid_with_warnings.js
This PR includes mainly a beta™ version of our new/upcoming test case management API.
Now you can
* `list`,
* `validate`,
* `create` and
* `update`
test cases using the `forge` CLI.
The test case related subcommand is: `test-case` (aliased as `testcase` and `tc`).
For all commands you need to provide the organisation UID. You can obtain this UIDs via:
```
forge organisation list
```
All new test case related commands require you to pass in a test case definition. All three subcommands accept:
* path to JavaScript definition
* test definition to be piped in via standard in
```
forge test-case list -o $ORGANISATION_UID
```
```
forge test-case create --organization $ORGANISATION_UID --name auth-service-basic cases/authentication/basic.js
```
Test Case name can be given explicitly via …
=> Test Base Management

cmd/login.go, cmd/root.go
This was not noticed for a while, but when there was no `.stormforger.toml` in the current directory or home directory, `forge` will fail complaining that no configuration could be found. This is bad for new users :)
While on it, I also improved the message after `forge login`.
=> Bug: Fail if no config found

cmd/datasource.go, cmd/organisation.go, cmd/testcase.go, cmd/testrun.go, cmd/testrun_list.go
Previously we failed with an error if a subcommand was missing.
Now we simply use corba's default and print the usage/help information.
=> Print help on missing subcommands

.goreleaser.yml, .travis.yml, Dockerfile
This PR adds a first, minimal docker build, which will make docker images of the CLI available under [`stormforger/cli`](https://hub.docker.com/r/stormforger/cli/).
The used `Dockerfile` is very minimalistic and only contains the binary currently.
=> Add Docker builds

cmd/testcase_launch.go, cmd/testrun_watch.go, cmd/utils.go
For CI integration it is useful to launch a test and watch it right away.
With this PR you can now do:
```
forge test-case launch xPSX5KXm --watch
```
which will trigger the test case to be launched and watch it until completion. Like with `forge test-run watch $TEST_RUN_UID` you can also specify a watch timeout.
See `--help` for more information.
=> Add --watch to test-case launch command

.goreleaser.yml, Dockerfile, api/testcase.go, cmd/datasource.go, cmd/organisation_list.go, cmd/root.go, cmd/testcase_create.go, cmd/testcase_list.go, cmd/testcase_update.go, cmd/testcase_validate.go, cmd/utils.go
* add `--json` for machine readable output on `organisation list` and `test-case list`
* add global `--default-organisation` flag and `defaults.organisation` TOML configuration to allow to define a fallback/default if no organisation UID is provided
* remove the requirement for organisation UID to be present when updating a test case
=> Improve Organisation/UID Handling

cmd/completion.go
cobra does support generation of bash and zsh completion scripts.
This PR adds `forge completion` to generate simple completion files. There are some more options we might be able to extend later, but this should at least add support for the basic commands.
=> Add completion command

README.md, api/organisation/main.go, api/testcase/main.go, cmd/testcase_create.go, cmd/testcase_launch.go, cmd/testcase_list.go, cmd/testcase_update.go, cmd/testcase_validate.go, cmd/utils.go
This PR enables the use of `$organisation/$testCase` to reference test cases instead of the resources' UIDs.
This is only implemented for `forge test-case {list,validate,create,update,launch}`. More commands will follow.
The `<test-case-ref>` or `<organisation-ref>` arguments are now mandatory and organisations defined in `.stormforger-organisation` or in `stormforger.toml` are no longer used. On the plus-side the arguments are now much less confusing because they are consistent.
List existing test cases for `tisba`'s organisation:
```
forge test-case list tisba
```
Validate a test case without saving it (within the limits of `tisba`'s organisation):
```
forge test-case validate tisba cases/simple.js
```
Create a test case (named `test_simple` inside `tisba`'s organisation):
```
forge …
```
=> test-case commands: Allow non UID references

cmd/testcase_launch.go, cmd/testrun_watch.go, cmd/utils.go
This PR allows to write durations for arguments.
Instead of
```
forge test-case launch acme-inc/checkout --watch --watch-timeout=5400
```
you now can write it much nicer like this
```
forge test-case launch acme-inc/checkout --watch --watch-timeout=1h30m
```
If you want to use seconds, you have to add `s`: `--watch-timeout=5400s`.
The same rules apply to `forge test-run watch --timeout=…`
Note that durations will  be rounded to the nearest seconds.
Thanks @denderello for pointing this out!
=> Support time.Duration --timeout and --wait-timeout

api/client.go, api/file_fixture.go, api/organisation.go, api/testcase.go, api/testrun.go, cmd/testcase_get.go, cmd/testrun_list.go, cmd/testrun_show.go
This PR adds `forge test-case get tisba/test_simple` which allows you to view/download the test case definition of a given test case.
* delint some function and variable names (`*Url` should be `*URL`, `*Http*` should be `*HTTP*`, etc.)
* remove unused Client.GetFileFixture
* add Client.fetch to reduce code duplication where the forge client simply fetches (via `GET`) from a resource
=> Add test-case get

api/testcase.go
In order to be able to detect when a test case was updated successfully on the CLI.
=> Report success if test case was updated

cmd/testcase_launch.go
In order to prevent panic when running the command without arguments.
=> Validate argument of launch command

api/testcase.go, cmd/testcase_create.go, cmd/testcase_update.go
#34 & #36 introduced a issue, that test case create and update won't output anything, especially not in case there are issues or errors.
We eventually want to parse and process the API error responses properly, but for now, just output the API response. This way you can see errors again.
=> Fix outputs for test case update & create commands

cmd/testrun_abort.go, cmd/testrun_show.go, cmd/testrun_watch.go
Better not to panic, if you forget an argument ;)
`forge test-run show` will currently panic, as `abort` and `watch`.
This PR just adds some checks to validate the number of arguments being passed.
=> Check argument count for test-run {abort,show,watch} commands

cmd/testcase_launch.go, cmd/testrun_watch.go, cmd/utils.go
We did not print the full test run "result"/show after `forge test-case launch foo/bar --watch` or `forge test-run watch foo/bar/23`. This is pretty useful though, because the current short output does not contain the test run summary, like basic statistics, checks and counters etc.
This PR also eliminates redundant calls to fetch test runs :)
=> Print test run after watching

README.md, api/testrun.go, cmd/testrun_dump.go, cmd/testrun_logs.go
We want to view the full traffic dump via cli. 
This PR adds a new command for test runs, example: `forge test-run dump [test_run_uid]`.
=> Added new command to get a dump file for test runs

api/testrun.go, api/testrun/main.go, cmd/testrun_nfr.go, testdata/nfr/simple.yml
This PR adds the `test-run nfr` subcommand to check if a finished test run passes your non-functional requirements.
Given the following YML file:
```yml
version: "0.1"
requirements:
- test.completed: true
- test.cluster.utilization.cpu:
select: total_avg
test: ["<=", 60]
- test.duration: [">", 600]
- http.latency:
enabled: false
select:
type: percentile
value: 99
test: ["<=", 9000]
- http.latency:
select:
type: percentile
value: 99
where:
status: ["<", 500]
tag:
- ec-purchase-card-discount
test: ["<", 5000]
```
You can do
```
forge test-run nfr acme-inc/shop/42 nfr/blackfriday.yml
```
and see if your test run passes your defined non-functional requirements:
If the checks fail, `forge` will exit with non-zero.
This feature is in a beta state. The YML format, especially the rules and …
=> Test Run NFR

api/client.go, api/file_fixture.go, api/filefixture/main.go, cmd/datasource.go, cmd/datasource_delete.go, cmd/datasource_download.go, cmd/datasource_list.go, cmd/datasource_move.go, cmd/datasource_push.go, cmd/datasource_show.go, cmd/login.go, cmd/root.go, cmd/utils.go
This PR will allow the usage of non-UID references to work with data sources.
The new pattern is now:
```console
$ forge datasource {get,ls,mv,push,rm,show} <organization-ref>
```
`<organization-ref>` can be the organiation name, `acme-inc` e.g. or the organisation's UID.
The flag `--default-organisation` has been removed without replacement.
=> Data Source Commands: Allow non UID references

api/testrun/main.go, cmd/testcase_launch.go, cmd/testrun_watch.go, cmd/utils.go
This PR adds `human` (or `text`) output format for `test-run watch` and `test-case launch … --watch` commands.
Currently the output is very simple:
```
$ forge tr watch acme-inc/shop/23
Test Run: 5ho1GO5y started now (est. end 1 minute from now)
[running] Progress: 1%
[running] Progress: 5%
[running] Progress: 9%
…
```
`--output=json` will result in the same output as before.
=> add human/text output for test run watch command

cmd/testcase_launch.go, cmd/testrun_nfr.go, cmd/utils.go
This PR adds a `--nfr-check-file` option to `forge test-case launch` command.
Example:
```console
$ forge test-case launch acme-inc/shop --nfr-check-file=nfr/blackfriday.yml
```
This is basically the same as
```console
$ forge test-case launch acme-inc/shop --watch
```
followed by
```console
$ forge test-run nfr acme-inc/shop/42 nfr/blackfriday.yml
```
When using the `--nfr-check-file` option, the output will look something like this:
```console
[status] Test Run: dZ10eSWt started not yet (est. end n/a)
[deploying]
[status] Test Run: dZ10eSWt started 1 second ago (est. end 58 seconds from now)
[running] Progress: 3%
…
[status] Test run ended...
[analysing]
[status] Test run ended...
[done]
Test finished, running non-functional checks...
✓ test completion expected to be == true; was true …
```
=> Add --nfr-check-file Option to Test Case Launch Command

README.md, api/file_fixture.go, cmd/datasource_push.go
This PR adds `--auto-field-names` to `forge datasource push` command.
It will tell the API to interpret the first row as header names. This is mutually exclusive with the `--name` option, but can be used when multiple files should be uploaded (unlike `--name`).
Also, this PR improves checking of `datasource push` command options:
* `--delimiter` must be exactly one character
* `--fields`, `--delimiter` and `--auto-field-names` cannot be used with `--raw`
=> Data Sources: Add --auto-field-names

cmd/datasource_push.go
We recently introduced automatic field name extraction for `datasource` in #47. But we discovered making the `--name` and `--auto-field-names` option mutual exclusive isn't helpful. Assigning a name to a datasource makes still sense even if we assign the field name automatically. We just can't use `--name` when pushing multiple files at once. This was already checked.
On the other hand manually assigning field names with `--fields` doesn't work well together with an automatic extraction. This PR now has `--fields` and `--auto-field-names` mutual exclusive.
=> --fields and --auto-field-names are mutual exclusive

api/file_fixture.go, cmd/datasource_push.go
* previously `forge datasource push` did stop on first issue. It now continues if there are further files to be uploaded
* on successful upload the name, number of items and column names are printed. This allows the user to check if the upload was okay and fields correctly detected.
=> Improve datasource push output and don't stop on first issue

api/testcase.go, api/testrun.go, cmd/testcase_list.go, cmd/testrun_list.go, cmd/utils.go
`--archived` will only list test runs or cases that have been archived.
Now, by default, **only archived** test runs or cases will be listed.
=> Test Case/Run: add --archived option

api/meta.go, api/testrun/main.go, cmd/testcase_launch.go, cmd/testrun_show.go
This PR will print test run configuration options to various commands:
* `test-run show` will now print information on region, sizing and advanced options
* `test-case launch` will now also print these infos
In addition to that, we now unmarshal some meta data (links to be specific) to print "human" URLs to access reports etc.
Also, `--output=json` was improved for launching test runs.
=> Add Test Configuration Info to outputs

cmd/testcase_create.go, cmd/testcase_update.go, cmd/testcase_validate.go, cmd/utils.go, testdata/cases/includes/base.js, testdata/cases/includes/helpers.js, testdata/cases/includes/session_base.js
With this PR you can now do simple client-side includes. This is a prototype and has to be seen as a first approach to make test cases more modular.
Given a test case like this:
```js
definition.setTarget("testapp.loadtest.party");
definition.setArrivalPhases([{
duration: 5 * 60,
rate: 50,
max_users: 2000
},
]);
//#include ./session_base.js
//#include /Users/basti/Documents/src/golang/src/github.com/stormforger/cli/testdata/cases/includes/helpers.js
function otherHelpers() {
// ...
}
```
using `test-case update` or `test-case create` commands, will yield in a case like this:
```js
definition.setTarget("testapp.loadtest.party");
definition.setArrivalPhases([{
duration: 5 * 60,
rate: 50,
max_users: 2000
},
]);
// == start include (testdata/cases/includes/session_base.js) …
```
=> Test Case: Add include magic comment

cmd/datasource.go, cmd/datasource_delete.go, cmd/datasource_download.go, cmd/datasource_list.go, cmd/datasource_move.go, cmd/datasource_push.go, cmd/datasource_show.go, cmd/testcase_create.go, cmd/testcase_list.go, cmd/testcase_validate.go, cmd/utils.go
* Renamed all user visible strings to organisation (from organization). 
* Code strings have been shortened to `orga` (in the `cmd/` package)
This was based on the default Use in `organisation.go`. We can also rename this the other way around, as the API seem to provide the `/organization` route.
=> *: Organization -> Organisation

Dockerfile
Fixes #61.
I also set the debian frontend to noninteractive which makes the docker build output a lot shorter and less noisy.
=> docker: Add forge user so we don't run as root. #61

api/client.go, api/har.go, cmd/testcase_create.go
This PR changes the behavior of `fileUploadRequest` to perform gzip compression on all files uploaded to the Stormforger API and upload it with an additional `content-encoding: gzip` header.
Additionally it reverts the HAR upload compression, as this is no longer needed.
This benefits users who upload large file fixtures or test cases.
Currently the API does not yet support this feature, as it is not a usual thing browser do. We have to support this by hand on the server side.
=> Add Gzip compression for all file uploads

.gitignore, cmd/testcase_update.go
* Test-case update now throws an exit=1 when the update itself fails
* Output is prefixed with INFO/WARN/ERROR based on command result
* Exit Code represents whether the tc was updated or not, not whether there was a validation error or not
```
$ ./forge test-case update zeisss ./demo.js
ERROR: Test case unknown
exit status 1
$ ./forge test-case update foo/demo ./demo.js
INFO: Test case updated
$ ./forge test-case update foo/demo ./demo.js
WARN: Test case updated, but contains issues which have to be addressed
1) E0: Invalid Attribute
Instance type 'c5.xlarge' is not available!
2) E0: Invalid Attribute
Maximum allowed c5.large instances is 11 instances
$ ./forge test-case update foo/demo ./demo.js
ERROR: Test case could not be updated
1) E23: Evaluation Error
ReferenceError: afasd is not …
```
=> Fix test-case update exit code for validation errors and validation output formatting

.goreleaser.yml
Fixes #77 
See https://goreleaser.com/deprecations/#brew for the deprecation notice.
=> goreleaser: Update brew step to plural due to deprecation of old variant (fixes #77)

cmd/har.go, cmd/testcase_create.go, cmd/testcase_update.go, cmd/testcase_validate.go, cmd/testrun_nfr.go, cmd/utils.go
* Refactored some utility functions so that you don't have to pass around ALL arguments to the cli
* `test-case validate` now accepts multiple file parameters
=> testcase: validate supports multiple filenames

cmd/testcase_launch.go
There is no need to pin the region for validation testruns anymore.
=> Allow any region for validation runs

api/client.go, api/file_fixture.go, api/testcase.go, api/testrun.go, cmd/utils.go
Small mixed bag:
* Always close response bodies after handling the response
* `time.Since()` is preferred over time.Now().Sub(start)
The former is especially important for long running scenarios i.e. while waiting for a test-run to finish, otherwise memory and network sockets will leak.
=> api: Close request body / use time.Since

.github/workflows/gobuild.yml
Travis still seems to be broken and does not provide any feedback for PRs. To prevent the most stupid mistakes of non-compiling code, lets add at least the `go build` stuff for now.
=> Add github action to verify + go build on push

cmd/testcase_launch.go
This makes the test-run uid available for later commands without having to parse the output or other black magic tricks.
Fixes #116
=> feat: Add --uid-file flag for exposing the test-run id

cmd/testrun_watch.go
Our nightly integration test-runs recently failed due to the state `finished.
With our new engine the `finished` state is now more visible to the endusers / api / cli, thus showing the fact we forgot to treat it correctly more often.
This PR adds it to our successful list.
=> feat: treat finished as a successful test-run outcome and do not fail the cli

cmd/testcase_launch.go, cmd/utils.go
With our legacy engine we had to disallow using nfr checks and traffic-dump together. This now works with our new loadtest engine. See https://docs.stormforger.com/reference/engine/ for more information.
Additionally this PR formats any NFR api error better instead of dumping just the raw (JSON) response.
=> feat: Allow NFR and traffic dump together

cmd/utils.go
Fixes #131 
This PR prints a summary of the number of nfr checks and how many have succesfully passed.
=> feat: print nfr summary line (fixes #131)

cmd/datasource_delete.go, cmd/datasource_download.go, cmd/datasource_list.go, cmd/datasource_move.go, cmd/datasource_push.go, cmd/datasource_show.go, cmd/testcase_create.go, cmd/testcase_get.go, cmd/testcase_launch.go, cmd/testcase_list.go, cmd/testcase_update.go, cmd/testcase_validate.go, cmd/testrun_list.go, cmd/utils.go, testdata/cases/valid.js
When integrating the `forge` cli into CI/CD pipelines it is annoying for having to create the test-case manually beforehand before running your CI/CD pipeline or even having to do a `forge tc create || forge tc update` fallback logic. 
* This PR adds the `--update` param to `forge test-case create` to allow for updating the test-case if it already exists.
* We aligned the output and exit-code behavior of `test-case create` with `test-case update`
Also:
* We also made the `lookupTestCase() ` function non-fatal and instead added a `mustLookupTestCase()` with the old behavior
* The removal of `*` in various calls to `NewClient()` was mainly out of "it-felt-dirty"
* We opted for adding this to `test-case create` as we already have all necessary parameters here. (we tried adding it to …
=> feat: Add --update flag to test-case create to update test-case if it already exists

api/testrun.go, api/testrun_test.go
Currently we return a confusing "could not download logs" when using `forge tr logs <uid>` with a UID that the user has no access to.
This PR returns a more helpful "test-run or logs not found" for `404 Not Found` status codes. This hopefully reduces the confusion a bit.
```
14:24 $ ./cli tr logs KR1c92R6g
2020/06/19 14:28:04 test-case or logs not found
```
=> feat: return a nicer error when we receive a 404 for the calllog/userlog

api/client.go, api/file_fixture.go, api/har.go, api/testcase.go, api/testrun.go, cmd/testcase_launch.go, cmd/utils.go
NOTE: This feature of the API is still in development. This does not yet work with the public API.
This adds a test-case-file parameter to test-case launch and uploads the file as part of the launch api call. The API is intended to update the test-case with this new definition and launch a test-run immediately.
```
$ forge tc launch sf_dev/sandbox --title="foo" --notes="bar" --dump-traffic --session-validation-mode=false --sizing=tiny --test-case-file=./test.js
Launching test sf_dev/sandbox/77
UID: u6FsTQfv
Web URL: http://127.0.0.1:3000/tr/u6FsTQfv
Configuration: tiny cluster in vagrant
[✓] Traffic Dump
```
=> feat: allow atomic update and launch for tests

cmd/testcase_launch.go
When adding the "Atomic Update & Launch" feature we forgot that the API can now return validation errors. We actually haven't parsed them nicely at all so far anyway.
This PR treats the response as a JSONAPI error (see https://jsonapi.org/format/#errors) and parses it via the same logic we use in `tc create` and `tc update`.
Note that we are updating the API to return JSONAPI Errors here for other validation errors as well.
=> fix: parse and format errors from the API for tc launch nicely

api/types.go, cmd/ping.go, cmd/ping_test.go
We recently added service-accounts which are organisation bound API tokens. These accounts have a unique token that can be used to talk for our API without having to register a shared dedicated user for your CI/CD pipeline or other integrations.
This PR updated the output of `forge ping` to print the service account label and UID instead of the email adress to better indicate that this is not a personal account you are operating on.
* Added new fields to `api.User` to store new response fields
* Refactored the ping command to construct a result object and hand it off to a printer for writing to stderr
* Added json support by replacing the formatter function with a json encoder, if output is `json`
* Added unit tests for the formatters
=> feat(cmd/ping):  print service account UID and name instead of email

cmd/datasource_delete.go, cmd/datasource_download.go, cmd/datasource_list.go, cmd/datasource_move.go, cmd/datasource_push.go, cmd/har.go, cmd/login.go
The datasource subcommands all had bugs where you could pass only one argument and the command would panic. This PR replaces our own argument length validation with the builtin cobra one.
=> refactor: use cobra.ExactArgs() and cobra.MinimumNArgs() for argument length validation

.goreleaser.yml, cmd/completion.go, cmd/datasource_delete.go, cmd/datasource_download.go, cmd/datasource_list.go, cmd/datasource_move.go, cmd/datasource_push.go, cmd/datasource_show.go, cmd/root.go, cmd/testcase_create.go, cmd/testcase_get.go, cmd/testcase_launch.go, cmd/testcase_list.go, cmd/testcase_update.go, cmd/testcase_validate.go, internal/stringutil/stringutil.go
This PR makes a breaking change the `forge completion` command, which generates completion scripts. It now accepts an argument to generate completion scripts for bash, zsh, fish or powershell.
Example:
```terminal
$ forge completion zsh > ./forge-zsh.sh
$ source ./forge-zsh.sh
```
This PR also adds dynamic completion for the following commands:
* root: `--ouput` is completed
* Test Case: Completion for `orga/test-case` references (or just `orga` where applicable)
* Test Case Launch:
* `--region` and `--sizing` flags are completed
* `test-case-file` and `nfr-check-file` have hints to filter for `*.js` and `*.yaml`
* Data Source commands do now complete the organisation
=> Improve Bash Completion

cmd/root.go
=> feat: Omit ANSI color escape sequences if NO_COLOR env var exists

cmd/testcase_launch.go
Make the error a bit more helpful then `Failed to open : esbuild failed`
=> fix: Print input filename when bundling fails

Dockerfile
Ubuntu 19.10 seems to fail when doing apt-get updates etc, so Ubuntu 20.04 it is.
=> Update docker image to ubuntu 20.04

cmd/datasource.go
It was overwritten for each of the datasource subcommands, so setting it does nothing and only creates confusion.
=> feat: remove broken --organisation flag for datasource subcommand

api/client.go
With a recent change to the way we serve File Fixtures (see ) the CLI is supposed to download the File from S3.
The forge CLI does perform a fingerprint check against all certificates and denies the request if the expected fingerprint is not present in the certificate chain.
This causes all File Fixture downloads in all existing CLI clients to fail:
```sh
forge ds get foo test_user.csv
2021/03/26 15:55:09 TLS Public Key could not be verified!
```
=> api/client.go: Skip fingerprint verification for non-forge hosts

api/client.go, api/testrun.go
Alternative to #219. With some recent StormForger API changes datasource files are now served gzip compressed. This breaks `ds get <org> <name>`, since compression support was disabled in the HTTP client.
* Enable compression support in the Go HTTP client so every response with compressed is handled transparently
* Remove manual gzip decompression in the `tc logs/dump` subcommands / api calls
@tisba Do you remember why this was disabled before?
=> fix: Enable compression for all api requests to fix datasource downlodas being compressed

.github/workflows/gobuild.yml, .github/workflows/release.yml, go.mod
This PR updates the CLI to use Go 1.16. I decided to give this a try, because I was looking into releasing [arm64 builds](https://github.com/stormforger/cli/pull/224).
* switch to reading go version from `go.mod`
* added `~/.cache/go-build` to cache paths (see [here](https://github.com/mvdan/github-actions-golang) for an interesting overview)
* remove unneeded `-mod=readonly` as this is the default for Go 1.16 anyway
=> Update to Go 1.16 and update GHA Workflows

.github/workflows/gobuild.yml, .github/workflows/release.yml
I noticed that we do have cache hits with very small or even empty caches:
It turns out, that GitHub action is using only the cache key and the fact that it got a hit for the cache. There is no "paths to cache have changed, let's change the cache" mechanism. We used the `actions/cache` step in a couple of places, where we did not use it afterwards like for `gofmt`. This leads to the problem that this job might run and finish first, and creates an empty cache, which other jobs will lookup and load. 🤦 
A similar problem happens for the release workflow: We used to first setup the cache and then wait for other jobs to finish. That might also lead to similar issues described before. We should wait first for other jobs and then setup everything (including hopefully warm caches).
=> Fix GitHub Action caching issues

.github/workflows/release.yml
This allows goreleaser to create a proper changelog from the git history. Without it, the changelog only contains the last commit
=> ci: Perform a full clone for the release pipeline

examples/README.md
The README in the `examples/` folder is intended to point users to various features, e.g. the javascript modularization.  The mentioned command `forge test-case build` by itself does not show the long help text, this requires the `--help` flag.
=> Add proper command for forge tc build

api/testrun.go, cmd/testcase_launch.go
**See:** https://trello.com/c/fCrRZ22x/364-labels-metadata
Accepting `--label key=value` args which are stored on a Test Run.
=> TestCase Launch Cmd: Accept --label key=value args

api/client.go
User reported a panic in `forge test-case launch` with a module file.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8f8685]
goroutine 1 [running]:
github.com/stormforger/cli/api.fileUploadRequest(0xc0002f6280, 0x45, 0xab3373, 0x4, 0xc000135488, 0xacba52, 0x27, 0x7ffe761fb44d, 0x17, 0xabf638, ...)
/home/runner/work/cli/cli/api/client.go:180 +0x3c5
github.com/stormforger/cli/api.(*Client).TestRunCreate(0xc000034800, 0x7ffe761fb41e, 0x14, 0x7ffe761fb47e, 0x10, 0x7ffe761fb497, 0x18, 0x7ffe761fb44d, 0x17, 0xb85720, ...)
/home/runner/work/cli/cli/api/testrun.go:221 +0x716
github.com/stormforger/cli/cmd.MainTestRunLaunch(0xc000034800, 0x7ffe761fb41e, 0x14, 0x0, 0x7ffe761fb47e, 0x10, 0x7ffe761fb497, …
```
=> fix: panic on test-case launch

cmd/testcase_launch.go
Related PR: https://github.com/stormforger/forge/pull/3578
See: https://trello.com/c/BhKTeXf9/686-make-pool-selectable-by-user-like-regions
We want to start accepting the `pool` identifier provided via the `--region` flag.
=> TestcaseLaunch: Remove region validation

api/client.go, api/testcase.go, api/testrun.go, cmd/testcase_archive.go, cmd/testcase_unarchive.go, cmd/testrun_archive.go, cmd/testrun_unarchive.go
We can currently archive and unarchive test runs and cases from the web UI, but not via the CLI. This PR will add archive and unarchive commands for test cases and test runs.
Adds an `archive` and `unarchive` subcommand to both the test-case and test-run commands. Adds api support to match updates to forge made in https://github.com/stormforger/forge/pull/3592. Also adds a `put` method to the api client that basically matches the existing `fetch` method, but performs an HTTP PUT.
Tested manually against a local forge instance.
None that I know of.
=> Add archive/unarchive commands for test cases and test runs

cmd/login.go
See: https://trello.com/c/ghpvvMxb
See also: https://stormkore.slack.com/archives/C020D8Q02BB/p1633974941003900
This PR updates the login text that is displayed when a user has an existing `.stormforger.toml` file. Instead of giving the user an `echo` command that can be used to append the JWT to their config file, we now display some simple instructions on how to add the token to the config file. This should ease confusion in cases where users might otherwise blindly append multiple tokens to their config file, and then be confused when only the first token is ever used.
=> Update login text

cmd/testcase_build_test.go, cmd/testdata/TestTestcaseBuild__DefineParam_main.mjs, cmd/testdata/TestTestcaseBuild__DefineParam_output.js, cmd/testdata/TestTestcaseBuild__WithUndefinedVariable_main.mjs, cmd/testdata/TestTestcaseBuild__WithUndefinedVariable_output.js
This PR adds two test cases to verify that `--define` works and generates no error. 
The example script was copied from the help message of `forge tc build --help` [src](https://github.com/stormforger/cli/blob/master/cmd/testcase_build.go#L54-L56) and thus it is important that this case actually works. So lets add a test for it ;)
=> tests: Add go tests for the 'forge tc build --define'

cmd/utils.go
An internal user tried using `--define` with his test-case and got this error that confused him:
```terminal
2022/02/07 04:28:13 WARN: --define used with non-module testcase file
<lots of validation / update errors by our API>
```
This changes the warning to hint the user to use the `.mjs` file extension.
=> fix: Add hint for .mjs file extension when showing usage warning

.github/workflows/gobuild.yml, .github/workflows/release.yml
We released a new `forge` version the other day. The release pipeline ran on Ubuntu 22.04 thus requiring the `forge` binary to require a newer GLIBC release.
This PR pins the release workflow to Ubuntu 20.04, thus making the binary compatible with older Ubuntu again (as well as the newest Ubuntu).
=> ci: Pin Ubuntu to 20.04 so forge binaries do not require newer GLIBC

api/testrun.go, api/testrun/testrun.go, cmd/testrun_shareurl.go
This adds a new subommand:
```terminal
forge test-run share-url my-org/demo/1
```
Optionally, the `--expire-duration` flag can be provided to customize the duration of the signed share url. By default, the expire-duration is determined by the API, which currently defaults to 1 year.
```terminal
$ forge tr share-url foo/test_simple/7  --output json
{
"url": "http://localhost:3000/s/tr:8wg8kxwg:test_simple:7?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cjo4d2c4a3h3ZyIsImV4cCI6MTcxODk5MjAwOCwiaWF0IjoxNjg3NDM1MDU2LCJqdGkiOiI4YjNiZmQiLCJzZl9jYnkiOiJ5dHlreWl2YiJ9.uF7u1T7TpPVhJMRlWrzcl4VGhggLeF-vL0wDtwNJLu8",
"expires_at": "2024-06-21T17:46:48Z"
}
$ forge tr share-url foo/test_simple/7
URL:		 http://localhost:3000/s/tr:8wg8kxwg:test_simple:7?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cjo4d2c4a3h3ZyIsImV4cC …
```
=> feat: Add forge tr share-url subcommand to create presigned URL for sharing reports

cmd/testcase_build_test.go, cmd/testdata/TestTestcaseBuild__DefineParam_main.mjs, cmd/testdata/TestTestcaseBuild__DefineParam_output.js, cmd/testdata/TestTestcaseBuild__WithUndefinedVariable_main.mjs, cmd/testdata/TestTestcaseBuild__WithUndefinedVariable_output.js, testdata/cases/index.mjs, testdata/cases/modules/options.js
Once upon a time we added some bundling tests in #304 which did not properly represent passing in values while also having a valid test case if not defining a value.
This PR updates the test-cases and the modules example to have a case that works when passing values via `--define` but also allows skipping those values.
=> fix: Update bundle tests to have proper example

.github/workflows/gobuild.yml, .github/workflows/release.yml
Pin all GH actions to their exact commit SHA.
Also: Removed the manual use of `actions/cache`, as this is no longer needed since [`actions/setup-go@v4`](https://github.com/actions/setup-go#v4):
> The action will try to enable caching unless the cache input is explicitly set to false.
=> Pin GH Actions

.github/workflows/go.yml, .github/workflows/release.yml
* ~update runner to Ubuntu 22.04 LTS~ we don't want to - I added a comment why
* renames `gobuild.yml` -> `go.yml` for consistency with other repos
* drops `jitterbit/await-check-suites` (which is unmaintained and outdated) and just re-build
=> GHA: Update runner OS, drop jitterbit/await-check-suites

api/testcase.go, cmd/testcase_create.go, cmd/testcase_launch.go, cmd/testcase_update.go, cmd/testcase_update_test.go, cmd/testcase_validate.go
Two smaller fixes:
* `forge tc create` did not print an error nor had a non-zero test-case for some API calls where we only returned a message, but nothing in the `errors` field. This will now always print the result
* Treat any 2xx as success for API TestcaseCreate()
* Cleanup feedback printing a bit
=> fix(testcase create): Do not relie on empty errors array to check for success

api/file_fixture.go, api/har.go, api/login.go, api/serviceaccount.go, api/testcase.go, api/testrun.go, cmd/login.go, cmd/testcase_build_test.go, cmd/testcase_get.go, cmd/testcase_launch.go
We noticed that we still send the default Go user agent string `go-http-client/???` for logins.
This PR fixes this as well as usage of the deprecated `io/ioutil`.
=> fix(api): Sent user-agent for login as well

cmd/ping.go
A user reported that their CI pipeline continued working although the `forge ping` command printed an error.
Expected behavior is for the `forge ping` command to have a non-zero exit code.
=> fix: forge ping returns an exit code when ping fails

.github/dependabot.yml
We are currently don't need to do many changes to the CLI, so we rarely do releases. There is no need to merge every single dependency update with so few releases. Lets switch to a monthly schedule to stay up to date.
We can still manually run the updates before doing an actual release.
=> chore(dependabot): Switch to monthly update schedule
