stormforger/cli

api/client.go
`forge ping` was broken :-/ (no authentication header was send so it always failed)
=> use Client.doRequestRaw for making ping requests

.travis.yml, api/client.go, api/file_fixture.go, api/har.go, api/testcase.go, cmd/datasource_push.go, cmd/har.go, cmd/root.go, cmd/testcase.go, cmd/testcase_validate.go, cmd/utils.go, testdata/cases/invalid.js, testdata/cases/valid.js
This PR provides new commands and API for the upcoming new test case APIs.
The first test case API will be to run basic validations of test case definitions.
Usage will be like: `forge test-case validate my_first_test_case.js`. For now the response will be pretty much 1:1 the response from the API (pretty printed JSON) as the response is not yet finalized and quite in flux:
```
forge test-case validate invalid_test_case.js
```
```json
{
"message": "invalid test case",
"error": {
"name": "SyntaxError",
"message": "Unexpected token ]",
"raw_stack": "SyntaxError: Unexpected token ]\n    at Function.execute (\u003canonymous\u003e:24:10)\n    at eval_wrapper (\u003canonymous\u003e:2:31)\n    at \u003canonymous\u003e:1:1",
"stack": {
"message": "SyntaxError: Unexpected token ]",
"frames": [
{ …
```
=> Test Case Validation

Makefile, README.md, api/client.go, api/har.go, api/login.go, cmd/datasource_download.go, cmd/root.go, cmd/test_run_logs.go, cmd/testcase_validate.go
I stumbled across [errcheck](https://github.com/kisielk/errcheck) and I used it to improve places all over the codebase to improve error handling.
=> Improved Error Handling

README.md
Working with data sources was not mentioned elsewhere, so I added a section to the README to clarify current usage.
=> README: Add infos on how to work with data sources

README.md, cmd/datasource_delete.go, cmd/datasource_download.go, cmd/datasource_move.go, cmd/datasource_show.go, cmd/utils.go
Extract lookup for `fileFixture` into a helper.
=> Refactoring: Data Source

README.md
As suggested by @denderello.
After logging in, you can use `forge ping` to easily check if your authentication works.
=> Add forge ping to README

Gopkg.lock, Gopkg.toml, README.md, cmd/login.go, vendor/github.com/mitchellh/go-homedir/LICENSE, vendor/github.com/mitchellh/go-homedir/README.md, vendor/github.com/mitchellh/go-homedir/homedir.go, vendor/github.com/mitchellh/go-homedir/homedir_test.go
This PR will slightly change the behaviour of `forge login`.
1. if `~/.stormforger.toml` does not exist, it will write the access token after successful authentication
1. remove `--email` flag (redundant and confusing)
💕 @zeisss
=> Improve login

README.md, cmd/datasource_download.go
This PR adds some missing updates to the README :)
=> Follow Up: Datasource non UID

api/testrun.go, cmd/testcase_launch.go
This PR will add the first test case launch options. This is currently focused on debug flags, but this will expand to more options over time.
These flags can be applied to the `forge test-case launch` command:
* `--disable-gzip`: Overwrite request for compressed data (don't send `Accept-Encoding: gzip` header)
* `--skip-wait`: Overwrite defined wait times and set them to 0.
* `--dump-traffic`: Request traffic dump to be recorded for this execution. **Note that with this option enabled, no report will be generated. Only a close-to-wire dump will be generated.**
=> Test Case Launch: Add Debug Launch Options

api/testrun.go, cmd/testcase_launch.go
This PR adds options for our new ability to override test case defined region and sizings.
=> Test Case Launch: add --region and --sizing options

cmd/testcase_validate.go
In #57 `test-case validate` was overlooked :)
=> TC: Error handling for Test Case Validation

cmd/testcase_launch.go
* Add missing regions
* Replaced manual list of regions with link to docs in `tc launch`
=> Regions update

Dockerfile
=> Changes Docker base image to Ubuntu 19.04

cmd/datasource_push.go
Improve the help texts for various flags to improve the understanding of the default behavior.
=> feat: improve flag help texts to show better default values

.github/dependabot.yml
See https://github.blog/changelog/2020-07-02-dependabot-updates-your-github-actions-workflows
=> ci: update github action workflows via dependabot

.github/workflows/gobuild.yml
=> chore: Update gobuild.yml to remove upload-artifact

.github/dependabot.yml
We missed something in #202
🤷‍♂️
=> Run dependabot weekly only

.goreleaser.yml
(this is based on #223)
I wanted to give an amd64 release a try to offer native binaries on Apple Silicon Macs.
=> Add ARM64 releases

cmd/testcase_build.go
This updates the output of `forge tc build --help` to the contents of our new advanced CLI usage guide at https://docs.stormforge.io/perftest/guides/advanced-cli-usage/.
This will also align with the bundling info from our platform CLI.
=> docs: Update tc build help text to content from docs

api/har.go
This PR adds the missing authentication headers to `forge har`.
=> feat(api): Add authentication headers to HAR request

go.mod
=> chore(go.mod): Bump go version to 1.23.4
